### ISSUE TITLE
CDN availability

### ISSUE THREAD

**Issue by smarts** [nicjansma/usertiming.js#12]
It would be awesome to get this on [cdnjs](https://cdnjs.com) and/or [jsDelivr](http://www.jsdelivr.com)

**Comment by nicjansma** [comment]
https://github.com/cdnjs/cdnjs/issues/5692 and https://github.com/jsdelivr/jsdelivr/pull/6874

**Comment by nicjansma** [comment]
http://www.jsdelivr.com/projects/usertiming.js

**Comment by smarts** [comment]
:tada: Thanks so much!

**Comment by nicjansma** [comment]
https://cdnjs.com/libraries/usertiming
